apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-service-hpa 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-service-deployment

  minReplicas: 2   # We always want at least 2 pods for high availability.
  maxReplicas: 5   # We will allow it to scale up to a maximum of 5 pods.

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # If the average CPU utilization across all api-service pods
        # goes above 50%, the HPA will create more pods to bring it back down.
        averageUtilization: 50